DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Group;
DROP TABLE IF EXISTS List;
DROP TABLE IF EXISTS Task;


CREATE TABLE User {
  id INTEGER PRIMARY KEY,
  username TEXT UNIQUE,
  email TEXT PRIMARY KEY,
  phoneNumber INTEGER UNIQUE,
  country TEXT UNIQUE,
  timeZone INTEGER NOT UNIQUE --UTC Offset
  fullName TEXT NOT NULL,
  birthDate DATE NOT NULL,
  passwordHash TEXT NOT NULL
};

CREATE TABLE Group {
  id INTEGER PRIMARY KEY,
  name TEXT UNIQUE,
  idUser INTEGER REFERENCES User (id)
};

CREATE TABLE List {
  id INTEGER PRIMARY KEY,
  name TEXT UNIQUE,
  idGroup INTEGER REFERENCES Group (id)
};


CREATE TABLE Task {
  id INTEGER PRIMARY KEY,
  idList INTEGER REFERENCES List (id)
};
